# Use the latest Ubuntu LTS as the base image
FROM ubuntu:20.04

# Set the DEBIAN_FRONTEND to noninteractive to suppress prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update the image and install system packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    wget \
    xvfb \
    zip \
    ca-certificates \
    libnss3-dev \
    libasound2 \
    libxss1 \
    libappindicator3-1 \
    libindicator7 \
    gconf-service \
    libgconf-2-4 \
    libpango1.0-0 \
    xdg-utils \
    fonts-liberation \
    wmctrl


# Set the working directory
WORKDIR /robot

RUN pip3 install robot/requirement.txt

# Copy the current directory contents into the container at /robot
COPY . /robot

# Copy the environment JSON file into the container at /robot/Runners/Environment/web_environment.json
COPY updated_env_web_1.json /robot/Runners/Environment/web_environment.json

# Execute the Robot Framework test cases
CMD ["robot","/robot/Web/RR/TestCases/Login/login_test.robot"]
