# Use Python as the base image
FROM python:3.9-slim

# Set the DEBIAN_FRONTEND to noninteractive to suppress prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update the image and install system packages
RUN apt-get update --fix-missing && apt-get install -y \
    wget \
    xvfb \
    zip \
    ca-certificates \
    libnss3-dev \
    libasound2 \
    libxss1 \
    libappindicator3-1 \
    libindicator7 \
    gconf-service \
    libgconf-2-4 \
    libpango1.0-0 \
    xdg-utils \
    fonts-liberation \
    wmctrl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy the requirements.txt to the working directory in the Docker image
COPY requirements.txt /robot/requirements.txt

# Install Python packages listed in requirements.txt
RUN pip install --no-cache-dir -r /robot/requirements.txt

# Set working directory
WORKDIR /robot

# Copy the test files to the working directory
COPY . /robot

# Set the default command to run Robot Framework with an option to specify tags
CMD ["robot", "--i", "DarkMode", "/robot/Web/RR/"]
