profileicon_dropdown = '//button[@class="btn-login btn-menu"]'
profileicon_icon = '//span[contains(text(),"My Profile")]'
lastname_profilepage_text = '//span[contains(@class,"last-name name")]/parent::h4'
firstname_profilepage_text = '//span[@class="first-name name"]'
editprofileicon_xpath = '//button[@aria-label="edit profile" and @type="button"]'
editprofilephoto_icon ='//button[@aria-controls="userProfilePhoto"]'
removeprofile_photo ='//button[@class="btn-remove"]'
confirmchanges_button ='//span[contains(text(),"Confirm Changes")]'
uploadphoto_xpath = '//input[@type="file"]'
setting_button ='//span[contains(text(),"Settings")]/parent::button'
membership_text ='//span[contains(text()," Membership Benefits")]'
joinnow_button ='//span[contains(text(),"join now")]/parent::button[@class="btn btn-fill"]'
setting_editprofile_button ='//span[contains(text(),"Edit Profile")]/parent::button[@class="btn-edit-profile"]'
nextbutton_loc ='//button[@aria-label="next"]'
fav_player_name = '//div[contains(@class,"player-name")]'
upload_img_button = '//div[@class="masthead-upload"]'
registered_date_xpath = '//div[contains(@class,"account-date")]//following-sibling::span[@class="text"]'
user_edit_button = '(//div[@class="profile-body"]//button[@class="btn-edit"])[{index}]'
update_jersey_numberbtn = '//button[@aria-controls="userJerseyNumber"]'
update_jersey_no_inputbox = '//input[@id="userJerseyNumber"]'
jersy_no_save_button = '//div[contains(@class,"jersey-no")]//button[@class="btn-save"]'
user_profile_data_xpath ='(//span[@class="text"])[{index}]'
jersy_number = '//span[@class="jersey-number"]'
for_you_section = '//h2[normalize-space()="For You"]'