royals_academy_link = '//a/span[text()="Royals Academy"]'
academy_registration_link = '//a/span[text()="Registration"]'
select_academy_dropdown = '//select[@name="academy"]'
academy_nagpur_option = '//select/option[text()="Nagpur (India)"]'
academy_dubai_option = '//select/option[text()="Dubai (UAE)"]'
academy_conrwall_option = '//select/option[text()="Conrwall (UK)"]'
academy_surrey_option = '//select/option[text()="Surrey (UK)"]'
first_name_academy = '//input[@name="firstName"]'
last_name_academy = '//input[@name="lastName"]'
email_academy = '//input[@name="academyEmail"]'
mobile_number_academy = '//input[@name="Mobile Number"]'
date_of_birth_academy = '//input[@name="academyDOB"]'
country_dropdown_academy = '//select[@name="academyCountry"]'
state_dropdown_academy = '//select[@name="academyState"]'
city_field_academy = '//input[@name="academyCity"]'
language_radio_button_academy = '//input[@name="language"]'
registration_submit_button = '//span[contains(text(),"Submit")]//parent::button'
invalid_email_message = '//span[@class="message" and text()="Invalid email"]'
invalid_mobile_message = '//span[@class="message" and text()="Mobile number should be atleast 10 digit"]'
