load_more_button = "//button[text()='Load More']"
table_row = '//div[@class="table-body"]//div[@class="table-row"]'
bottom_element = "//p[text()='Title Sponsor']"
filter_stats_button = "//span[text()='Filter']//parent::button"
filter_by_skills_stats = '//div[@class="filter-actions"]//following::p[text()="Filter By Skills"]'
filter_by_stats = '//div[@class="filter-actions"]//following::p[text()="Filter By Stats"]'
filter_by_teams_stats = '//div[@class="filter-actions"]//following::p[text()="Filter By Teams"]'
batting_dropdown_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Batting"]'
bowling_dropdown_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Bowling"]'
fielding_dropdown_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Fielding"]'
most_wickets_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Most Wickets"]'
best_bowling_inning_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Best Bowling Innings"]'
best_bowling_average_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Best Bowling Average"]'
most_5_wickets_haul_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Most Five Wicket Hauls"]'
best_economy_rates_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Best Economy Rates"]'
best_bowling_strike_rate_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Best Bowling Strike Rate"]'
most_expensive_bowler_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Most Expensive Bowler"]'
most_maidens_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Most Maidens"]'
five_wicket_haul_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Five Wicket Haul"]'
three_wicket_haul_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Three Wicket Haul"]'
apply_filters_stats = "//span[text()='Apply Filters']"
wickets_stats_name = "//span[text()='WKTS']"
wickets_stats_rows = '//div[@class="table-body"]//following::div[@class="table-data active wickets"]'
bbi_rows = '//div[@class="table-body"]//following::div[contains(@class,"table-data active")]'
avg_rows = '//div[@class="table-body"]//following::div[@class= "table-data active best-bowling-average"]'
economy_rows = '//div[@class="table-body"]//following::div[contains(@class,"active economy")]'
s_r_rows = '//div[@class="table-body"]//following::div[@class="table-data active"]'
five_wickets_rows = '//div[@class="table-body"]//following::div[contains(@class,"five-wickets-haul")]'
#
maiden_rows = '//div[@class="table-body"]//following::div[contains(@class,"active most-maidens")]'
five_wicket_haul_rows = '//div[@class="table-body"]//following::div[contains(@class,"active five-wickets-haul")]'
three_wicket_haul_rows = '//div[@class="table-body"]//following::div[contains(@class,"active three-wickets-haul")]'
most_runs_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Most Runs"]'
runs_rows = '//div[@class="table-body"]//following::div[contains(@class,"active runs")]'
highest_runs = '//div[@class="filter-actions"]//following::button[normalize-space()="Highest Score"]'
highest_runs_rows = '//div[@class="table-body"]//following::div[contains(@class,"active highest-score")]'
best_batting_average_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Best Batting Average"]'
best_strike_rate_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Best Strike Rate"]'
best_batting_average_rows = '//div[@class="table-body"]//following::div[contains(@class,"active average")]'
best_strike_rate_rows = '//div[@class="table-body"]//following::div[contains(@class,"active strike-rate")]'
most_hundreds_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Most Hundreds"]'
most_hundreds_rows = '//div[@class="table-body"]//following::div[contains(@class,"active 100s")]'
most_fifties_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Most Fifties"]'
most_fifties_rows = '//div[@class="table-body"]//following::div[contains(@class,"active 50s")]'
most_fours_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Most 4s"]'
most_six_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Most 6s"]'
most_fours_rows = '//div[@class="table-body"]//following::div[contains(@class,"active 4s")]'
most_six_rows = '//div[@class="table-body"]//following::div[contains(@class,"active 6s")]'
most_catches_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Most Catches"]'
most_catches_rows = '//div[@class="table-body"]//following::div[contains(@class,"active most-catches")]'
most_dismissals_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Most Dismissals"]'
most_dismissals_rows = '//div[@class="table-body"]//following::div[contains(@class,"active most-dismissals")]'
most_run_outs_stats = '//div[@class="filter-actions"]//following::button[normalize-space()="Most Run Outs"]'
most_run_outs_rows = '//div[@class="table-body"]//following::div[contains(@class,"active most-run-outs")]'