name: Build and Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build, Tag, and Push Images to Amazon ECR
      - name: Build, Tag, and Push Images to Amazon ECR
        id: build-and-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: si_repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          DOCKERFILES=$(find . -name 'Dockerfile*')
          > image-uris.txt
          
          for DOCKERFILE in $DOCKERFILES; do
            BASENAME=$(basename $DOCKERFILE)
            TAG=${BASENAME//Dockerfile_/}
            TAG=${TAG:-default}
            
            IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$TAG-$IMAGE_TAG"
            
            echo "Building and pushing Docker image for $DOCKERFILE to $IMAGE_URI"
            
            docker build -f $DOCKERFILE -t $IMAGE_URI .
            docker push $IMAGE_URI
            
            echo "$TAG:$IMAGE_URI" >> image-uris.txt
          done

          # Set IMAGE_URI output
          echo "::set-output name=image_uri::$IMAGE_URI"

      # Verify Image URIs
      - name: Verify Image URIs
        run: |
          echo "Contents of image-uris.txt:"
          cat image-uris.txt

      # Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version

      # Create S3 Bucket for Robot Framework Results
      - name: Create S3 Bucket for Robot Framework Results
        run: |
          BUCKET_NAME="my-robot-results-bucket"
          if ! aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
            echo "Bucket does not exist. Creating bucket..."
            aws s3api create-bucket --bucket $BUCKET_NAME --region us-east-1
          else
            echo "Bucket already exists. Skipping creation."
          fi

      # Create Log Group
      - name: Create Log Group
        run: |
          aws logs create-log-group --log-group-name /ecs/si-task || true

      # Get Default VPC ID
      - name: Get Default VPC ID
        id: default-vpc
        run: |
          VPC_ID=$(aws ec2 describe-vpcs --filters "Name=isDefault,Values=true" --query "Vpcs[0].VpcId" --output text)
          echo "Default VPC ID: $VPC_ID"
          echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV
          
      - name: Create Security Group
        id: create-security-group
        run: |
          SECURITY_GROUP_NAME="my-security-group"
          VPC_ID="${{ env.VPC_ID }}"
          
          SECURITY_GROUP_ID=$(aws ec2 describe-security-groups --filters "Name=group-name,Values=$SECURITY_GROUP_NAME" "Name=vpc-id,Values=$VPC_ID" --query 'SecurityGroups[0].GroupId' --output text)

          if [ "$SECURITY_GROUP_ID" == "None" ]; then
            echo "Creating security group $SECURITY_GROUP_NAME..."
            SECURITY_GROUP_ID=$(aws ec2 create-security-group --group-name $SECURITY_GROUP_NAME --description "My security group" --vpc-id $VPC_ID --query 'GroupId' --output text)
          else
            echo "Security group $SECURITY_GROUP_NAME already exists with ID $SECURITY_GROUP_ID."
          fi
          
          echo "SECURITY_GROUP_ID=$SECURITY_GROUP_ID" >> $GITHUB_ENV

      - name: Get Default Subnets
        id: default-subnets
        run: |
          VPC_ID="${{ env.VPC_ID }}"
          SUBNETS=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" --query "Subnets[*].SubnetId" --output text)
          # Format subnets as a comma-separated list
          FORMATTED_SUBNETS=$(echo $SUBNETS | tr '\t' ',')
          echo "Default Subnets: $FORMATTED_SUBNETS"
          echo "SUBNETS=$FORMATTED_SUBNETS" >> $GITHUB_ENV

      # Create ECS Cluster
      - name: Create ECS Cluster
        run: |
          aws ecs create-cluster --cluster-name si-cluster --region us-east-1 || true

      # Register ECS Task Definition
      - name: Register ECS Task Definition
        id: register-task-def
        run: |
          CLUSTER_NAME=si-cluster
          TASK_DEFINITION_NAME=si-task

          DOCKERFILES=$(find . -name 'Dockerfile*')
          CONTAINERS_JSON=""
          PORT=8080  # Starting port for containerPort and hostPort
          CONTAINER_CPU=256  # CPU units for each container
          CONTAINER_MEMORY=512  # Memory for each container
          TOTAL_CPU=0
          TOTAL_MEMORY=0

          echo "Reading image URIs from image-uris.txt..."
          cat image-uris.txt

          # Read image URIs from the file
          while IFS=: read -r TAG IMAGE_URI; do
            CONTAINER_NAME="${TAG}-container"

            TOTAL_CPU=$((TOTAL_CPU + CONTAINER_CPU))
            TOTAL_MEMORY=$((TOTAL_MEMORY + CONTAINER_MEMORY))

            if [ $TOTAL_CPU -le 1024 ] && [ $TOTAL_MEMORY -le 2048 ]; then
              CONTAINERS_JSON+="{
                \"name\": \"$CONTAINER_NAME\",
                \"image\": \"$IMAGE_URI\",
                \"essential\": true,
                \"memory\": $CONTAINER_MEMORY,
                \"cpu\": $CONTAINER_CPU,
                \"portMappings\": [
                  {
                    \"containerPort\": $PORT,
                    \"hostPort\": $PORT
                  }
                ],
                \"logConfiguration\": {
                  \"logDriver\": \"awslogs\",
                  \"options\": {
                    \"awslogs-group\": \"/ecs/$TASK_DEFINITION_NAME\",
                    \"awslogs-region\": \"us-east-1\",
                    \"awslogs-stream-prefix\": \"$CONTAINER_NAME\"
                  }
                }
              },"

              PORT=$((PORT + 1))  # Increment port for next container
            else
              echo "Skipping container $CONTAINER_NAME due to resource limits."
            fi
          done < image-uris.txt

          # Remove the trailing comma
          CONTAINERS_JSON=${CONTAINERS_JSON%,}

          TASK_DEF_JSON="{
            \"family\": \"$TASK_DEFINITION_NAME\",
            \"networkMode\": \"awsvpc\",
            \"containerDefinitions\": [
              $CONTAINERS_JSON
            ],
            \"requiresCompatibilities\": [\"FARGATE\"],
            \"cpu\": \"1024\",
            \"memory\": \"2048\",
            \"executionRoleArn\": \"arn:aws:iam::533267409793:role/ecsTaskExecutionRole\"
          }"

          echo "$TASK_DEF_JSON" > task-definition.json
          aws ecs register-task-definition --cli-input-json file://task-definition.json

      - name: Deploy ECS Service
        run: |
          CLUSTER_NAME="si-cluster"
          SERVICE_NAME="si-service"
          TASK_DEFINITION_NAME="si-task"
          SUBNETS="${{ env.SUBNETS }}"
          SECURITY_GROUP_ID="${{ env.SECURITY_GROUP_ID }}"

          # Check if the service exists
          SERVICE_EXISTS=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query 'services[0].serviceName' --output text 2>/dev/null || echo "MISSING")

          if [ "$SERVICE_EXISTS" == "MISSING" ]; then
            echo "Service $SERVICE_NAME does not exist. Creating service..."
            aws ecs create-service \
              --cluster $CLUSTER_NAME \
              --service-name $SERVICE_NAME \
              --task-definition $TASK_DEFINITION_NAME \
              --desired-count 1 \
              --launch-type FARGATE \
              --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS],securityGroups=[$SECURITY_GROUP_ID],assignPublicIp=ENABLED}"
          else
            echo "Service $SERVICE_NAME already exists. Updating service..."
            aws ecs update-service \
              --cluster $CLUSTER_NAME \
              --service $SERVICE_NAME \
              --task-definition $TASK_DEFINITION_NAME \
              --desired-count 1
          fi

          
      # Run Robot Framework Tests
      - name: Run Robot Framework Tests
        run: |
          docker run --rm \
            -v $PWD:/robot \
            ${{ steps.build-and-push.outputs.IMAGE_URI }}
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Push the Robot Framework logs to S3 with a timestamp
      - name: Upload Robot Framework Logs to S3
        run: |
          LOG_DIR="log"
          if [ -d "$LOG_DIR" ]; then
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            aws s3 cp "$LOG_DIR" "s3://my-robot-results-bucket/$TIMESTAMP/" --recursive
            echo "Logs uploaded to S3 with timestamp: $TIMESTAMP"
          else
            echo "Log directory does not exist. Skipping upload."
          fi
